docs: add fetching once tip
vuejs/vuefire pull request #1323
Opened 2023-03-13 17:13 UTC by davidstackio

2023-07-03 13:40 UTC, posva requested changes
Let's keep this section untouched and add a new section "Fetching data once" with a short example similar to the realtime example

2023-07-05 20:36 UTC, davidstackio commented
@posva is this what you had in mind?

2023-07-06 05:29 UTC, posva approved these changes
Thanks!

2023-07-06 05:29 UTC, posva commented on docs/guide/realtime-data.md
> +import { useDatabaseList } from 'vuefire'
```suggestion
import { useDatabaseList, useDatabaseObject } from 'vuefire'
```

2023-07-06 05:29 UTC, posva commented on docs/guide/realtime-data.md
> +</template>
```suggestion
```

2023-07-06 05:29 UTC, posva commented on docs/guide/realtime-data.md
> +</template>
```suggestion
```

2023-07-06 05:29 UTC, posva commented on docs/guide/realtime-data.md
> +</script>
```suggestion
```

2023-07-06 05:29 UTC, posva commented on docs/guide/realtime-data.md
> +<script setup>
```suggestion
```ts{3,4}
```

2023-07-06 05:29 UTC, posva commented on docs/guide/realtime-data.md
> +<script setup>
```suggestion
```ts{3,4}
```

2023-07-06 05:29 UTC, posva commented on docs/guide/realtime-data.md
> +</script>
```suggestion
```

2023-07-06 05:29 UTC, posva commented on docs/guide/realtime-data.md
> +To fetch data only _once_, use the [`once`](https://vuefire.vuejs.org/api/interfaces/UseDocumentOptions.html#once) option, which will retrieve a snapshot of the data:
```suggestion
To fetch data only _once_, pass the [`once`](https://vuefire.vuejs.org/api/interfaces/UseDocumentOptions.html#once) option, which will automatically destroy the subscription as soon as the document or collection is completely fetched:
```

2023-07-12 12:00 UTC, merged