fix: bindFirestoreRef not reacting to getter
vuejs/vuefire pull request #1496
Opened 2024-02-21 22:45 UTC by ralacerda

Closes #1495

Checking if the `docOrCollectionRef` is a ref before setting up a watch to re-bind the firestore meant getters weren't being watched. 

Using `watch(() => toValue(docOrCollectionRef), bindFirestoreRef)` will keep the old behaviour of tracking refs and computeds while also tracking getters.

In this case, we also don't need to check what `docOrCollectionRef` is.
Unless there is a cost in watching an non-reactive source (I don't think so, but I'm not sure).

I'm still learning my way around the tests, I tried the following, but the tests hangs and fails:

```ts
it('can be bound to a getter', async () => {
  const listCollectionRef = collection<{ name: string }>()
  const listRef = ref<null | CollectionReference>(null)

  const { wrapper } = factory({
    ref: () => listRef.value,
  })

  await addDoc(listCollectionRef, { name: 'a' })
  await addDoc(listCollectionRef, { name: 'b' })

  expect(wrapper.vm.list).toHaveLength(0)
  listRef.value = listCollectionRef
  expect(wrapper.vm.list).toContainEqual({ name: 'a' })
  expect(wrapper.vm.list).toContainEqual({ name: 'b' })
})
```

But I must be doing something wrong because even when I use `ref: listRef` it also fails, but `ref: listCollectionRef` it works.
I'll keep the PR as a draft while I work on those tests.

2024-02-22 09:41 UTC, posva requested changes
For the test: rather than using a ref of a collection, put a string in the ref and use `() => collection(db, '...', myRef.value)`

2024-02-22 09:41 UTC, posva commented on src/firestore/useFirestoreRef.ts
> -  if (isRef(docOrCollectionRef)) {
Let's keep isRef or typeof is function

2024-02-22 09:41 UTC, posva commented on src/firestore/useFirestoreRef.ts
> +  stopWatcher = watch(() => toValue(docOrCollectionRef), bindFirestoreRef)
Since the getter function returns the actual value, toValue shouldn't be needed

2024-02-22 09:41 UTC, posva commented on src/firestore/useFirestoreRef.ts
> -  if (isRef(docOrCollectionRef)) {
BTW, it is for performance reasons

2024-02-22 09:43 UTC, posva commented
Could you also add the same for `useDatabaseRef.ts` and `storage.ts`?

2024-02-22 22:53 UTC, ralacerda commented
I returned the `isRef` checking but also included `typeof === 'function'` as you suggested.

I wrote a test for `useDatabase` that it's pretty similar to the one above.

I was able to add a test for `useDocument` with your suggestion.

The current test uses an named collection (`populatedCollection` and `emptyCollection`) which I guess can be a problem if another test tries to use the same named collection. 

Should I use `collection()` util to create an unique collection for this test, and then, inside it create and document and `populatedCollection`?

Something like
```diff

it('can be bound to a getter', async () => {
-  const listCollectionRef = collection<{ name: string }>(
-    'populatedCollection'
-  )
+  const parentCollectionName = collection().path.split('/').at(-1)
+  const populatedCollection = collection<{ name: string }>(
+    parentCollectionName,
+    'parentDocument',
+    'populatedCollection'
+  )
  const collectionName = ref('populatedCollection')

  const { wrapper, promise } = factory({
-    ref: () => collection(collectionName.value),
+    ref: () =>
+      collection(
+        parentCollectionName,
+        'parentDocument',
+        collectionName.value
+      ),
  })

  await promise.value
-  await addDoc(listCollectionRef, { name: 'a' })
-  await addDoc(listCollectionRef, { name: 'b' })
+  await addDoc(populatedCollection, { name: 'a' })
+  await addDoc(populatedCollection, { name: 'b' })

  expect(wrapper.vm.list).toHaveLength(2)
  expect(wrapper.vm.list).toContainEqual({ name: 'a' })
  expect(wrapper.vm.list).toContainEqual({ name: 'b' })

  collectionName.value = 'emptyCollection'
  await nextTick()
  await promise.value
  await nextTick()
  expect(wrapper.vm.list).toHaveLength(0)
})

```

I wanted to ask because I'm not sure if it's really needed.

2024-02-23 07:55 UTC, posva commented
It should be fine the way you did it it, no need to create a subcollection 🙂

2024-02-23 07:55 UTC, posva approved these changes
Thanks a lot!

2024-02-23 07:55 UTC, merged

2024-02-23 07:57 UTC, posva commented
I published a patch 👍